### ISSUE TITLE
Confusion over java options

### ISSUE THREAD

**Issue by shawkins** [jboss-dockerfiles/infinispan#73]
It looks like there are three way java options are referenced.  

- https://github.com/jboss-dockerfiles/infinispan/blob/40234d6551c4013e0068867f6c20cc8457d39689/server/docker-entrypoint.sh#L307 - mentions JAVA_OPTIONS, should that just be JAVA_OPTS?

- JAVA_OPTS are only used in some of the CONTAINER_SETTINGS paths.  Is that intended, or should they be exported always?

- And additional options can be passed in as extra parameters to the script and will be part of SERVER_OPTIONS.

Can you clarify if I'm reading this correctly?

**Comment by slaskawi** [comment]
> - mentions JAVA_OPTIONS, should that just be JAVA_OPTS?

 Yes, that's correct. It's a bug.

> JAVA_OPTS are only used in some of the CONTAINER_SETTINGS paths. Is that intended, or should they be exported always?

Yes it is intended. If you specify `-n|--no-container-settings` parameters, we don't want to modify JAVA_OPTS at all. 

However there's actually a bug since we define `JAVA_OPTS` in a wrong place: https://github.com/jboss-dockerfiles/infinispan/blob/40234d6551c4013e0068867f6c20cc8457d39689/server/docker-entrypoint.sh#L198

> And additional options can be passed in as extra parameters to the script and will be part of SERVER_OPTIONS.

Yes. `SERVER_OPTIONS` parameter can be used for specifying configuration file for example.

**Comment by slaskawi** [comment]
I'm closing this one. If there's something more to clarify, please reopen.
